### ISSUE TITLE
npm package of ngx-zone-scheduler 2.0.1 still contains .git directory

### ISSUE THREAD

**Issue by egandro** [Jovalent/ngx-zone-scheduler#3] opened 2018-06-02 11:29 UTC
+1 :)

npm package of ngx-zone-scheduler 2.0.1 still contains the .git directory

**Comment by errorx666** [comment] 2018-06-02 17:45
I pit .git in the npmignore file.

What am I doing wrong?

**Comment by egandro** [comment] 2018-06-02 18:11
No idea if ".git/" is right.

Add "more"

.git/**
.git

or - simply rm -rf .git or move it temprarly to ..

**Comment by errorx666** [comment] 2018-06-03 19:47
Fixed in 42789c5f53fca584882c1ed2b36ebb0e7f8a2fc2.

Duplicate of #2.

**Closed by errorx666** 2018-06-03 19:47 UTC

**Comment by egandro** [comment] 2018-06-04 17:30
Thx a lot!
